'use client';

import { useState } from 'react';
import type { InvestigationReport } from '@/lib/types';
import { getVerdictLabel, getVerdictColor, getConfidenceLabel } from '@/lib/types';
import ClaimMediaConsistency from './ClaimMediaConsistency';
import EvidenceGraph from './EvidenceGraph';
import MediaTimeline from './MediaTimeline';
import CounterfactualPanel from './CounterfactualPanel';
import SourceIndependence from './SourceIndependence';
import ExplainabilityPanel from './ExplainabilityPanel';
import ProvenancePassport from './ProvenancePassport';
import TranscriptPanel from './TranscriptPanel';
import SocialDebunkCardModal from './SocialDebunkCardModal';
import { 
  ShieldCheck, 
  ShieldAlert, 
  HelpCircle, 
  Info,
  FileImage,
  MessageSquare,
  History,
  Scale,
  AlertTriangle,
  Sparkles,
  CheckCircle2,
  XCircle,
  AlertCircle,
  Share2,
  Download,
  LayoutGrid,
  GitGraph,
  Clock,
  ScanEye,
  Sliders,
  FileCheck2,
  Globe2
} from 'lucide-react';

interface ReportViewProps {
  report: InvestigationReport;
  isShared?: boolean;
}

export default function ReportView({ report, isShared = false }: ReportViewProps) {
  const [activeTab, setActiveTab] = useState('overview');
  const [isDebunkModalOpen, setIsDebunkModalOpen] = useState(false);
  
  const colorName = getVerdictColor(report.verdict);
  
  // Choose icon based on verdict category
  const VerdictIcon = 
    colorName === 'green' ? ShieldCheck :
    colorName === 'red' || colorName === 'amber' ? ShieldAlert :
    HelpCircle;

  let explanation = report.summary;
  let largeLabel = getVerdictLabel(report.verdict);

  if (report.investigationId === 'real-false-context') {
    largeLabel = 'Real Media, False Context';
    explanation = 'The photo/video itself is authentic, but the attached story or claim is completely misleading.';
  }

  // Quick plain-English takeaways
  const isImageAuthentic = report.fileAuthenticity >= 60;
  const isClaimAccurate = report.claimAccuracy >= 60;

  const tabs = [
    { id: 'overview', label: 'Summary & Facts', icon: LayoutGrid, desc: 'Overall verdict and quick breakdown' },
    { id: 'graph', label: 'Evidence Graph', icon: GitGraph, desc: 'Visual connection between sources and claims' },
    { id: 'timeline', label: 'Timeline', icon: Clock, desc: 'When this media first appeared online' },
    { id: 'explainability', label: 'AI Forensics', icon: ScanEye, desc: 'Visual, audio, and face analysis' },
    { id: 'counterfactual', label: 'What-If Tests', icon: Sliders, desc: 'How changes would alter the outcome' },
    { id: 'provenance', label: 'Digital Passport', icon: FileCheck2, desc: 'File signatures, hashes, and metadata' },
    { id: 'sources', label: 'Web Sources', icon: Globe2, desc: 'Independent news and fact-check matches' },
  ];

  return (
    <div className="space-y-6 animate-fade-in-up max-w-5xl mx-auto">
      
      {/* ── Optional Alerts ────────────────────────────── */}
      {isShared && (
        <div className="rounded-xl border border-accent-amber/30 bg-accent-amber-dim p-4 flex items-start gap-3">
          <Info className="h-5 w-5 text-accent-amber shrink-0 mt-0.5" />
          <p className="text-sm font-semibold text-accent-amber leading-relaxed">
            Shared Investigation Report: This report is generated by AI evidence analysis and provides decision support.
          </p>
        </div>
      )}

      {report.requiresHumanReview && !isShared && (
        <div className="rounded-xl border border-accent-amber/40 bg-accent-amber-dim/50 p-4 flex items-start gap-3">
          <AlertTriangle className="h-5 w-5 text-accent-amber shrink-0 mt-0.5" />
          <p className="text-sm font-semibold text-accent-amber leading-relaxed">
            Human Review Recommended: The evidence gathered is mixed. Review the source matches below for full context.
          </p>
        </div>
      )}

      {/* ── 1. Hero Verdict Card (Clear & Bold) ────────────────────────────── */}
      <section className={`rounded-2xl border bg-card p-6 sm:p-8 relative overflow-hidden transition-all
        ${colorName === 'green' ? 'border-accent-green/40 shadow-xl shadow-accent-green/10' : ''}
        ${colorName === 'amber' ? 'border-accent-amber/40 shadow-xl shadow-accent-amber/10' : ''}
        ${colorName === 'red' ? 'border-accent-red/40 shadow-xl shadow-accent-red/10' : ''}
        ${colorName === 'blue' ? 'border-accent-blue/40 shadow-xl shadow-accent-blue/10' : ''}
      `}>
        {/* Ambient background glow */}
        <div className={`absolute top-0 right-0 w-80 h-80 -mr-20 -mt-20 rounded-full blur-3xl opacity-15 pointer-events-none
          ${colorName === 'green' ? 'bg-accent-green' : ''}
          ${colorName === 'amber' ? 'bg-accent-amber' : ''}
          ${colorName === 'red' ? 'bg-accent-red' : ''}
          ${colorName === 'blue' ? 'bg-accent-blue' : ''}
        `} />

        <div className="relative z-10 space-y-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center gap-5">
            <div className={`flex items-center justify-center w-16 h-16 rounded-2xl shrink-0 shadow-inner
              ${colorName === 'green' ? 'bg-accent-green/15 text-accent-green border border-accent-green/30' : ''}
              ${colorName === 'amber' ? 'bg-accent-amber/15 text-accent-amber border border-accent-amber/30' : ''}
              ${colorName === 'red' ? 'bg-accent-red/15 text-accent-red border border-accent-red/30' : ''}
              ${colorName === 'blue' ? 'bg-accent-blue/15 text-accent-blue border border-accent-blue/30' : ''}
            `}>
              <VerdictIcon className="h-8 w-8" />
            </div>

            <div className="flex-1 space-y-1">
              <div className="flex flex-wrap items-center justify-between gap-2.5">
                <div className="flex items-center gap-2.5">
                  <span className="text-xs uppercase tracking-wider font-semibold text-muted">Final Verdict</span>
                  <span className={`px-2.5 py-0.5 rounded-full text-[11px] font-bold uppercase tracking-wider
                    ${colorName === 'green' ? 'bg-accent-green/10 text-accent-green border border-accent-green/20' : ''}
                    ${colorName === 'amber' ? 'bg-accent-amber/10 text-accent-amber border border-accent-amber/20' : ''}
                    ${colorName === 'red' ? 'bg-accent-red/10 text-accent-red border border-accent-red/20' : ''}
                    ${colorName === 'blue' ? 'bg-accent-blue/10 text-accent-blue border border-accent-blue/20' : ''}
                  `}>
                    Confidence: {getConfidenceLabel(Math.round((report.evidenceStrength + report.provenanceConfidence) / 2))}
                  </span>
                </div>

                <button
                  type="button"
                  onClick={() => setIsDebunkModalOpen(true)}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-accent-blue text-white text-xs font-bold shadow-lg shadow-accent-blue/25 hover:shadow-accent-blue/40 hover:-translate-y-0.5 active:translate-y-0 transition-all"
                >
                  <Share2 className="h-3.5 w-3.5" />
                  1-Click Social & WhatsApp Debunk Card
                </button>
              </div>

              <h1 className={`text-2xl sm:text-4xl font-extrabold tracking-tight
                ${colorName === 'green' ? 'text-accent-green' : ''}
                ${colorName === 'amber' ? 'text-accent-amber' : ''}
                ${colorName === 'red' ? 'text-accent-red' : ''}
                ${colorName === 'blue' ? 'text-accent-blue' : ''}
              `}>
                {largeLabel}
              </h1>
            </div>
          </div>

          {/* Simple Explanation / TL;DR */}
          <div className="rounded-xl bg-background/70 border border-card-border p-4 sm:p-5">
            <p className="text-xs uppercase font-bold text-accent-blue mb-1 flex items-center gap-1.5">
              <Sparkles className="h-3.5 w-3.5" />
              What this means in plain words:
            </p>
            <p className="text-foreground text-sm sm:text-base leading-relaxed">
              {explanation}
            </p>
          </div>

          {/* 3 Quick Takeaway Badges for Non-Technical Users */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 pt-1">
            <div className="flex items-center gap-3 rounded-lg bg-background/50 border border-card-border px-3.5 py-2.5">
              {isImageAuthentic ? (
                <CheckCircle2 className="h-5 w-5 text-accent-green shrink-0" />
              ) : (
                <XCircle className="h-5 w-5 text-accent-red shrink-0" />
              )}
              <div>
                <p className="text-[11px] text-muted font-medium">Is media genuine?</p>
                <p className="text-xs font-bold text-foreground">
                  {isImageAuthentic ? 'Yes (Real Capture)' : 'No (AI / Edited)'}
                </p>
              </div>
            </div>

            <div className="flex items-center gap-3 rounded-lg bg-background/50 border border-card-border px-3.5 py-2.5">
              {isClaimAccurate ? (
                <CheckCircle2 className="h-5 w-5 text-accent-green shrink-0" />
              ) : (
                <AlertCircle className="h-5 w-5 text-accent-amber shrink-0" />
              )}
              <div>
                <p className="text-[11px] text-muted font-medium">Is the story true?</p>
                <p className="text-xs font-bold text-foreground">
                  {isClaimAccurate ? 'Accurate Context' : 'Misleading / False Story'}
                </p>
              </div>
            </div>

            <div className="flex items-center gap-3 rounded-lg bg-background/50 border border-card-border px-3.5 py-2.5">
              <ShieldCheck className={`h-5 w-5 shrink-0 ${colorName === 'green' ? 'text-accent-green' : colorName === 'red' ? 'text-accent-red' : 'text-accent-amber'}`} />
              <div>
                <p className="text-[11px] text-muted font-medium">Should you share?</p>
                <p className="text-xs font-bold text-foreground">
                  {colorName === 'green' ? 'Safe to Share' : colorName === 'red' ? 'Do Not Share' : 'Caution / Misleading'}
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── 2. Simplified 4 Key Metric Cards ────────────────────────────── */}
      <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        
        {/* File Authenticity */}
        <div className="rounded-xl border border-card-border bg-card p-5 space-y-3 hover:border-muted/40 transition-colors">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="p-1.5 rounded-lg bg-accent-blue/10 text-accent-blue">
                <FileImage className="h-4 w-4" />
              </div>
              <div>
                <h3 className="text-xs font-bold text-foreground uppercase tracking-wider">Visual Integrity</h3>
                <p className="text-[10px] text-muted">Is the file original?</p>
              </div>
            </div>
            <span className="text-2xl font-black text-foreground">{report.fileAuthenticity}%</span>
          </div>
          <div className="h-2 w-full bg-background rounded-full overflow-hidden">
            <div 
              className={`h-full rounded-full transition-all duration-700 ${report.fileAuthenticity > 70 ? 'bg-accent-green' : report.fileAuthenticity > 40 ? 'bg-accent-amber' : 'bg-accent-red'}`} 
              style={{ width: `${report.fileAuthenticity}%` }} 
            />
          </div>
        </div>

        {/* Claim Accuracy */}
        <div className="rounded-xl border border-card-border bg-card p-5 space-y-3 hover:border-muted/40 transition-colors">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="p-1.5 rounded-lg bg-accent-blue/10 text-accent-blue">
                <MessageSquare className="h-4 w-4" />
              </div>
              <div>
                <h3 className="text-xs font-bold text-foreground uppercase tracking-wider">Claim Accuracy</h3>
                <p className="text-[10px] text-muted">Is the caption true?</p>
              </div>
            </div>
            <span className="text-2xl font-black text-foreground">{report.claimAccuracy}%</span>
          </div>
          <div className="h-2 w-full bg-background rounded-full overflow-hidden">
            <div 
              className={`h-full rounded-full transition-all duration-700 ${report.claimAccuracy > 70 ? 'bg-accent-green' : report.claimAccuracy > 40 ? 'bg-accent-amber' : 'bg-accent-red'}`} 
              style={{ width: `${report.claimAccuracy}%` }} 
            />
          </div>
        </div>

        {/* Provenance */}
        <div className="rounded-xl border border-card-border bg-card p-5 space-y-3 hover:border-muted/40 transition-colors">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="p-1.5 rounded-lg bg-accent-blue/10 text-accent-blue">
                <History className="h-4 w-4" />
              </div>
              <div>
                <h3 className="text-xs font-bold text-foreground uppercase tracking-wider">History Trace</h3>
                <p className="text-[10px] text-muted">Can we find its origin?</p>
              </div>
            </div>
            <span className="text-2xl font-black text-foreground">{report.provenanceConfidence}%</span>
          </div>
          <div className="h-2 w-full bg-background rounded-full overflow-hidden">
            <div 
              className={`h-full rounded-full transition-all duration-700 ${report.provenanceConfidence > 70 ? 'bg-accent-green' : report.provenanceConfidence > 40 ? 'bg-accent-amber' : 'bg-accent-red'}`} 
              style={{ width: `${report.provenanceConfidence}%` }} 
            />
          </div>
        </div>

        {/* Evidence Strength */}
        <div className="rounded-xl border border-card-border bg-card p-5 space-y-3 hover:border-muted/40 transition-colors">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <div className="p-1.5 rounded-lg bg-accent-blue/10 text-accent-blue">
                <Scale className="h-4 w-4" />
              </div>
              <div>
                <h3 className="text-xs font-bold text-foreground uppercase tracking-wider">Proof Level</h3>
                <p className="text-[10px] text-muted">How sure is the AI?</p>
              </div>
            </div>
            <span className="text-2xl font-black text-foreground">{report.evidenceStrength}%</span>
          </div>
          <div className="h-2 w-full bg-background rounded-full overflow-hidden">
            <div 
              className={`h-full rounded-full transition-all duration-700 ${report.evidenceStrength > 70 ? 'bg-accent-green' : report.evidenceStrength > 40 ? 'bg-accent-amber' : 'bg-accent-red'}`} 
              style={{ width: `${report.evidenceStrength}%` }} 
            />
          </div>
        </div>

      </section>

      {/* ── 3. Intuitive Tab Navigation ────────────────────────────── */}
      <section className="rounded-2xl border border-card-border bg-card overflow-hidden shadow-sm">
        
        {/* Navigation Bar */}
        <div className="border-b border-card-border bg-background/30 overflow-x-auto">
          <div className="flex w-max min-w-full px-2 gap-1 py-1.5">
            {tabs.map((tab) => {
              const TabIcon = tab.icon;
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`flex items-center gap-2 px-4 py-2.5 rounded-xl text-xs sm:text-sm font-semibold transition-all whitespace-nowrap ${
                    isActive
                      ? 'bg-accent-blue text-white shadow-md shadow-accent-blue/20'
                      : 'text-muted hover:text-foreground hover:bg-card'
                  }`}
                >
                  <TabIcon className={`h-4 w-4 ${isActive ? 'text-white' : 'text-muted'}`} />
                  {tab.label}
                </button>
              );
            })}
          </div>
        </div>

        {/* Tab Content Panel */}
        <div className="p-6 sm:p-8 min-h-[350px]">
          {activeTab === 'overview' && (
            <div className="space-y-8">
              {/* Voice Analysis Transcript Panel */}
              {report.voiceAnalysis && (
                <TranscriptPanel data={report.voiceAnalysis} />
              )}
              
              {report.voiceAnalysis && (report.claimMediaConsistency || report.findings.length > 0) && (
                <hr className="border-card-border" />
              )}

              {/* Claim vs Media Consistency */}
              {report.claimMediaConsistency && (
                <ClaimMediaConsistency data={report.claimMediaConsistency} />
              )}

              {/* Findings */}
              <div className="space-y-4">
                <div className="flex items-center gap-2">
                  <h3 className="text-base font-bold text-foreground uppercase tracking-wider">Key Findings & Signals</h3>
                </div>
                {report.findings && report.findings.length > 0 ? (
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {report.findings.map((finding) => (
                      <div key={finding.id} className="rounded-xl bg-background/50 border border-card-border p-5 space-y-2 hover:border-accent-blue/30 transition-all">
                        <h4 className="text-sm font-bold text-foreground flex items-center gap-2">
                          <span className="w-2 h-2 rounded-full bg-accent-blue"></span>
                          {finding.title}
                        </h4>
                        <p className="text-xs text-muted leading-relaxed">{finding.description}</p>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-sm text-muted">No findings detailed for this overview.</p>
                )}
              </div>
            </div>
          )}

          {activeTab === 'graph' && (
            <div className="space-y-4">
              <div>
                <h3 className="text-base font-bold text-foreground">Evidence Relationship Web</h3>
                <p className="text-xs text-muted">Click or hover over nodes to explore how the claim connects to verified data points.</p>
              </div>
              <EvidenceGraph
                nodes={report.knowledgeGraph?.nodes || []}
                edges={report.knowledgeGraph?.edges || []}
              />
            </div>
          )}

          {activeTab === 'timeline' && (
            <div className="space-y-4">
              <div>
                <h3 className="text-base font-bold text-foreground">Media & Story Timeline</h3>
                <p className="text-xs text-muted">Chronological footprint of when this image/video first appeared on the web versus the claim date.</p>
              </div>
              <MediaTimeline events={report.timeline || []} />
            </div>
          )}

          {activeTab === 'counterfactual' && (
            <div className="space-y-4">
              <div>
                <h3 className="text-base font-bold text-foreground">What-If Simulation Tests</h3>
                <p className="text-xs text-muted">Testing whether changing specific factors (e.g. removing compression) alters the verdict.</p>
              </div>
              <CounterfactualPanel counterfactuals={report.counterfactuals || []} />
            </div>
          )}

          {activeTab === 'sources' && (
            <div className="space-y-4">
              <div>
                <h3 className="text-base font-bold text-foreground">Matched Web & News Sources</h3>
                <p className="text-xs text-muted">Fact-checks, official government releases, and news reports that reference this media.</p>
              </div>
              {report.sourceIndependence ? (
                <SourceIndependence data={report.sourceIndependence} />
              ) : (
                <p className="text-sm text-muted">No external web source clustering available.</p>
              )}
            </div>
          )}

          {activeTab === 'explainability' && (
            <div className="space-y-4">
              <div>
                <h3 className="text-base font-bold text-foreground">Visual & Audio Forensic Heatmaps</h3>
                <p className="text-xs text-muted">Deep inspection into lighting anomalies, face boundaries, audio frequencies, and lip synchronization.</p>
              </div>
              <ExplainabilityPanel data={report.explainability} />
            </div>
          )}

          {activeTab === 'provenance' && (
            <div className="space-y-4">
              <div>
                <h3 className="text-base font-bold text-foreground">Digital Signature & Provenance Passport</h3>
                <p className="text-xs text-muted">Cryptographic hashes (SHA-256), perceptual fingerprint (pHash), and Content Credentials (C2PA).</p>
              </div>
              <ProvenancePassport data={report.provenance} isShared={isShared} />
            </div>
          )}
        </div>
      </section>

      {/* ── Social Debunk Card Modal ────────────────────────────── */}
      <SocialDebunkCardModal
        report={report}
        isOpen={isDebunkModalOpen}
        onClose={() => setIsDebunkModalOpen(false)}
      />

    </div>
  );
}
